### ISSUE TITLE
Git mergetools update

### ISSUE THREAD

**Issue by j4nu5** [whiteinge/eseth#3]
Thanks for the excellent article - https://www.eseth.org/2020/mergetools.html#hideresolved

Small comment - the article (in the aforementioned section) says - "At the time of this writing the proposal is to enable the flag by default."

You may want to note that this setting is off by default in the final implementation - https://git-scm.com/docs/git-mergetool#Documentation/git-mergetool.txt-mergetoolhideResolved - "Defaults to false".

**Comment by whiteinge** [comment]
Updated. Thanks for the note!
